[package]
name = "grpc-impl"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.14.2"


[build-dependencies]
tonic-build = "0.14.2"
tonic-prost-build = "0.14.2"
